### ISSUE TITLE
Help!!!!

### ISSUE THREAD

**Issue by Alkaid3Zz** [ubc-tea/SADM-Longitudinal-Medical-Image-Generation#3]
Hello, I am a college student, and I am currently studying this model. However, when I run it, I only see random noise. Could you please provide me with a complete code for learning purposes? Thank you.

**Comment by wltjr1007** [comment]
Sorry for the very late reply. I've completly lost track of this project, and I will get to uploading the code as soon as possible.

In the meantime, closing this issue as it is a duplicate of #1.

**Comment by 2ZiZ2** [comment]
你好，我现在运行还是遇到了马赛克，请问您上传新的代码了吗？
